# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: shairdo_dev
  username: shairdo
  password: shairdo
  host: localhost 

test:
  adapter: postgresql
  database: shairdo_test
  username: shairdo
  password: shairdo
  host: localhost 

production:
  adapter: postgresql
  database: shairdo_live
  username: shairdo
  password: shairdo
  host: localhost 
